version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gcp2.rule=Host(`gcp.fabiorvs.dev.br`)"
      - "traefik.http.routers.gcp2.entrypoints=websecure"
      - "traefik.http.routers.gcp2.tls=true"
      - "traefik.http.routers.gcp2.tls.certresolver=letsencrypt"
      - "traefik.http.services.gcp2.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
