services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./config/service.json:/var/www/config/service.json:ro
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - GOOGLE_CLOUD_PROJECT_ID=projeto-teste-378716
      - GOOGLE_CLOUD_KEY_FILE_PATH=config/service.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=cdse-prd
      - COMPOSER_ALLOW_SUPERUSER=1

    labels:
      - "traefik.http.routers.gcp2.rule=Host(`gcp.fabiorvs.dev.br`)"
      - "traefik.http.routers.gcp2.entrypoints=websecure"
      - "traefik.http.routers.gcp2.tls=true"
      - "traefik.http.routers.gcp2.tls.certresolver=letsencrypt"
      - "traefik.http.services.wordpress.loadbalancer.server.port=9000"

    ports:
      - "9000:9000"

    networks:
      - web

networks:
  web:
    external: true
